# My starship config for macOS
#  ï¼lã€
#ï¼ˆï¾Ÿï½¤ ï½¡ï¼—
#â € lã€ï¾~ãƒ½
#  ã˜ã—(_,)ãƒ

# Compact for better workflow ğŸ‘“
add_newline = false

# One line prompt because two line prompts dont look good ğŸ—‘ï¸
[line_break]
disabled = true

# This is why you need nerd font ğŸ¤“
[character]
success_symbol = "[ó°”](bold green)"
error_symbol = "[ó°”](bold green)"

# Home icon instead of '~' ğŸ 
[directory]
home_symbol = ' ó°‹œ '

# Get rid of ugly "took 1m" â°
[cmd_duration]
min_time = 0
format = ''
